name: 🔁 Test Hotfix Flow

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-meta:
    runs-on: ubuntu-latest
    outputs:
      merge_mode: ${{ steps.meta.outputs.merge_mode }}
      tag: ${{ steps.meta.outputs.tag }}
      branches: ${{ steps.meta.outputs.branches }}

    steps:
      - name: 🚦 Sync Metadata from PR
        id: meta
        uses: b3bb0/sync-hotfix-meta@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  handle-hotfix:
    needs: sync-meta
    if: startsWith(github.head_ref, 'hotfix/')
    uses: b3bb0/action-hotfix-handler/.github/workflows/hotfix-handler.yml@v1
    with:
      pr_number: ${{ github.event.pull_request.number }}
      pr_title: ${{ github.event.pull_request.title }}
      source_branch: ${{ github.head_ref }}
      merge_mode: ${{ needs.sync-meta.outputs.merge_mode }}
      tag: ${{ needs.sync-meta.outputs.tag }}
      branches: ${{ needs.sync-meta.outputs.branches }}
