
name: 🔁 Test Hotfix Flow

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  call-hotfix-handler:
    if: startsWith(github.head_ref, 'hotfix/')
    uses: b3bb0/action-hotfix-handler/.github/workflows/final.yml@v1
    with:
      pr_number: ${{ github.event.pull_request.number }}
      pr_title: ${{ github.event.pull_request.title }}
      source_branch: ${{ github.head_ref }}
